# Generated by Django 6.1 on 2026-08-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='local_aquisicao',
            field=models.CharField(default='Não informado', max_length=180),
        ),
    ]
