import { useState, type FormEvent } from 'react'
import './App.css'
type Page='Visão geral'|'Estoque'|'Entradas'|'Saídas'|'Funcionários'|'Análises'|'Configurações'
type Product={id:number;nome:string;localAquisicao:string;quantidade:number;minimo:number}
type Movement={id:number;tipo:'Entrada'|'Saída';produto:string;quantidade:number;origem:string;destino:string;responsavel:string;data:string;observacao:string}
type Person={id:number;nome:string;funcao:string;email:string}
const nav:Page[]=['Visão geral','Estoque','Entradas','Saídas','Funcionários','Análises']
const initialProducts:Product[]=[{id:1,nome:'Camiseta vermelha',localAquisicao:'Fornecedor central',quantidade:124,minimo:25},{id:2,nome:'Boné bordado',localAquisicao:'Gráfica Popular',quantidade:38,minimo:40},{id:3,nome:'Adesivo institucional',localAquisicao:'Distribuidora PT',quantidade:560,minimo:100}]
const initialMoves:Movement[]=[{id:1,tipo:'Entrada',produto:'Camiseta vermelha',quantidade:40,origem:'Fornecedor central',destino:'Almoxarifado',responsavel:'André Martins',data:'24/08/2026, 09:40',observacao:'Reposição de lote'},{id:2,tipo:'Saída',produto:'Boné bordado',quantidade:12,origem:'Almoxarifado',destino:'Evento regional',responsavel:'Marina Souza',data:'23/08/2026, 16:15',observacao:'Evento regional'}]
export default function App(){
 const [page,setPage]=useState<Page>('Visão geral'),[open,setOpen]=useState(false),[notice,setNotice]=useState(''),[products,setProducts]=useState(initialProducts),[moves,setMoves]=useState(initialMoves),[people,setPeople]=useState<Person[]>([{id:1,nome:'André Martins',funcao:'Administrador',email:'andre@exemplo.com'},{id:2,nome:'Marina Souza',funcao:'Coordenadora',email:'marina@exemplo.com'}])
 const select=(p:Page)=>{setPage(p);setOpen(false)}
 const addProduct=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),nome=String(f.get('nome')).trim();if(!nome)return;setProducts([...products,{id:Date.now(),nome,localAquisicao:String(f.get('local_aquisicao')),quantidade:Number(f.get('quantidade'))||0,minimo:Number(f.get('minimo'))||0}]);e.currentTarget.reset();setNotice('Produto cadastrado com sucesso.')}
 const addMove=(e:FormEvent<HTMLFormElement>,tipo:'Entrada'|'Saída')=>{e.preventDefault();const f=new FormData(e.currentTarget),id=Number(f.get('produto')),qty=Number(f.get('quantidade')),p=products.find(x=>x.id===id);if(!p||qty<1)return;if(tipo==='Saída'&&qty>p.quantidade){setNotice('A saída não pode superar o estoque disponível.');return}setProducts(products.map(x=>x.id===id?{...x,quantidade:x.quantidade+(tipo==='Entrada'?qty:-qty)}:x));setMoves([{id:Date.now(),tipo,produto:p.nome,quantidade:qty,origem:String(f.get('origem')),destino:String(f.get('destino')),responsavel:String(f.get('responsavel'))||'Não informado',data:new Date().toLocaleString('pt-BR'),observacao:String(f.get('observacao'))},...moves]);e.currentTarget.reset();setNotice(tipo+' registrada com sucesso.')}
 const addPerson=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),nome=String(f.get('nome')).trim();if(!nome)return;setPeople([...people,{id:Date.now(),nome,funcao:String(f.get('funcao')),email:String(f.get('email'))}]);e.currentTarget.reset();setNotice('Responsável cadastrado com sucesso.')}
 const exportCsv=()=>{const lines=['Tipo;Produto;Quantidade;Origem;Destino;Responsável;Data;Observação',...moves.map(x=>[x.tipo,x.produto,x.quantidade,x.origem,x.destino,x.responsavel,x.data,x.observacao].join(';'))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8;'}));a.download='historico-estoque.csv';a.click();URL.revokeObjectURL(a.href)}
 const low=products.filter(x=>x.quantidade<=x.minimo).length
 return <div className="app-shell"><aside className={'sidebar '+(open?'is-open':'')}><div className="brand"><span className="brand-mark">★</span><span>Gestão<br/><strong>PT</strong></span><button className="mobile-close" onClick={()=>setOpen(false)}>×</button></div><nav><p className="nav-label">MENU PRINCIPAL</p>{nav.map(x=><button key={x} onClick={()=>select(x)} className={page===x?'active':''}><span className="nav-dot"/> {x}</button>)}<p className="nav-label settings-label">SISTEMA</p><button onClick={()=>select('Configurações')} className={page==='Configurações'?'active':''}><span className="nav-dot"/>Configurações</button></nav><div className="support-card"><b>Perfil administrador</b><small>Permissões e cadastros protegidos.</small></div><div className="profile"><div className="avatar">AM</div><div><strong>André Martins</strong><small>Administrador</small></div></div></aside>{open&&<button className="backdrop" onClick={()=>setOpen(false)}/>}
 <main><header className="topbar"><button className="menu-toggle" onClick={()=>setOpen(true)}>☰</button><div className="search">⌕ <input placeholder="Buscar produtos, pessoas..."/></div><button className="notification" onClick={()=>setNotice('Você tem '+low+' alerta(s) de estoque baixo.')}>♧<i/></button></header><section className="content"><div className="page-heading"><div><p className="eyebrow">GESTÃO DE ESTOQUE</p><h1>{page==='Visão geral'?'Olá, André':page} {page==='Visão geral'&&<span>👋</span>}</h1><p className="subtitle">{description(page)}</p></div>{page==='Análises'&&<button className="primary-button" onClick={exportCsv}>↓ Gerar Excel</button>}</div>
 {page==='Visão geral'&&<Dashboard products={products} moves={moves} people={people}/>}
 {page==='Estoque'&&<Stock products={products} addProduct={addProduct}/>}
 {page==='Entradas'&&<MovementPage title="Registrar entrada" type="Entrada" products={products} people={people} moves={moves} submit={addMove}/>}
 {page==='Saídas'&&<MovementPage title="Registrar saída" type="Saída" products={products} people={people} moves={moves} submit={addMove}/>}
 {page==='Funcionários'&&<People people={people} submit={addPerson}/>}
 {page==='Análises'&&<Analysis moves={moves} products={products}/>}
 {page==='Configurações'&&<Settings/>}</section></main>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>
}
function description(p:Page){return ({'Visão geral':'Acompanhe a movimentação do seu estoque hoje.','Estoque':'Cadastre produtos e consulte o histórico de cadastro.','Entradas':'Registre novas entradas e consulte o histórico geral.','Saídas':'Registre saídas e acompanhe cada retirada.','Funcionários':'Cadastre e consulte os funcionários responsáveis.','Análises':'Histórico completo para conferência e exportação.','Configurações':'Controle o acesso dos perfis operadores.'}[p])}
function Dashboard({products,moves,people}:{products:Product[];moves:Movement[];people:Person[]}){return <><div className="stats-grid"><Stat title="Itens em estoque" value={String(products.reduce((a,x)=>a+x.quantidade,0))}/><Stat title="Movimentações" value={String(moves.length)}/><Stat title="Estoque baixo" value={String(products.filter(x=>x.quantidade<=x.minimo).length)}/><Stat title="Responsáveis" value={String(people.length)}/></div><article className="card products-card"><Header title="Últimas movimentações" text="Entradas e saídas registradas recentemente"/><History rows={moves.slice(0,5)}/></article></>}
function Stock({products,addProduct}:{products:Product[];addProduct:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="page-grid"><Form title="Cadastrar produto" submit={addProduct} fields={[['nome','Nome do produto'],['local_aquisicao','Local onde foi comprado/adquirido'],['quantidade','Quantidade inicial','number'],['minimo','Estoque mínimo','number']]}/><article className="card products-card"><Header title="Estoque e histórico de cadastro" text="Produtos cadastrados no sistema"/><div className="table-wrap"><table><thead><tr><th>PRODUTO</th><th>LOCAL DE AQUISIÇÃO</th><th>SALDO</th><th>SITUAÇÃO</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.nome}</strong></td><td>{p.localAquisicao}</td><td><strong>{p.quantidade} un.</strong></td><td><span className={'badge '+(p.quantidade<=p.minimo?'low':'good')}>{p.quantidade<=p.minimo?'Estoque baixo':'Em estoque'}</span></td></tr>)}</tbody></table></div></article></div>}
function MovementPage({title,type,products,people,moves,submit}:{title:string;type:'Entrada'|'Saída';products:Product[];people:Person[];moves:Movement[];submit:(e:FormEvent<HTMLFormElement>,type:'Entrada'|'Saída')=>void}){return <div className="page-grid"><article className="card form-card"><Header title={title} text={type==='Entrada'?'Informe a origem e o destino do material recebido.':'Registre a origem e o destino da retirada.'}/><form onSubmit={e=>submit(e,type)}><label>Nome do produto<select name="produto" required><option value="">Selecione</option>{products.map(p=><option value={p.id} key={p.id}>{p.nome} — {p.quantidade} un.</option>)}</select></label>{type==='Saída'&&<label>Quantidade<input name="quantidade" type="number" min="1" required/></label>}{type==='Entrada'&&<label>Quantidade<input name="quantidade" type="number" min="1" required/></label>}<label>Local de origem<input name="origem" required placeholder={type==='Saída'?'Destino registrado na entrada ou novo local':'Ex.: fornecedor, doação'}/></label><label>Local de destino<input name="destino" required placeholder={type==='Entrada'?'Ex.: almoxarifado':'Ex.: evento, unidade'}/></label><label>Funcionário responsável<select name="responsavel" required><option value="">Selecione</option>{people.map(p=><option key={p.id}>{p.nome}</option>)}</select></label><label>Anotações<textarea name="observacao" placeholder="Informações adicionais"/></label><button className="primary-button">Registrar {type.toLowerCase()}</button></form></article><article className="card products-card"><Header title={'Histórico de '+type.toLowerCase()} text="Registros mais recentes"/><History rows={moves.filter(m=>m.tipo===type)}/></article></div>}
function People({people,submit}:{people:Person[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="page-grid"><Form title="Cadastrar funcionário" submit={submit} fields={[['nome','Nome completo'],['funcao','Função dentro do gabinete'],['email','E-mail','email']]}/><article className="card products-card"><Header title="Lista de funcionários" text="Equipe responsável cadastrada"/><div className="table-wrap"><table><thead><tr><th>NOME</th><th>FUNÇÃO</th><th>E-MAIL</th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><strong>{p.nome}</strong></td><td>{p.funcao}</td><td>{p.email}</td></tr>)}</tbody></table></div></article></div>}
function Analysis({moves,products}:{moves:Movement[];products:Product[]}){return <><div className="stats-grid"><Stat title="Histórico geral" value={String(moves.length)}/><Stat title="Entradas" value={String(moves.filter(x=>x.tipo==='Entrada').length)}/><Stat title="Saídas" value={String(moves.filter(x=>x.tipo==='Saída').length)}/><Stat title="Cadastros de estoque" value={String(products.length)}/></div><article className="card products-card"><Header title="Histórico completo para análise" text="Movimentações de entrada e saída"/><History rows={moves}/></article></>}
function Settings(){const [role,setRole]=useState('OPERADOR');return <div className="page-grid"><article className="card form-card"><Header title="Criar perfil com autenticação" text="Todo novo perfil inicia como operador."/><form onSubmit={e=>e.preventDefault()}><label>Nome<input required/></label><label>E-mail<input type="email" required/></label><label>Senha<input type="password" minLength={8} required/></label><label>Cargo<select value={role} onChange={e=>setRole(e.target.value)}><option value="OPERADOR">Operador</option><option value="ADMIN">Administrador</option></select></label>{role==='ADMIN'&&<label>Código de administrador<input name="codigo_admin" required placeholder="Código de autorização"/></label>}<button className="primary-button">Criar perfil autenticado</button></form></article><article className="card products-card"><Header title="Permissões de operadores" text="Somente administradores podem alterar acessos."/><div className="permission"><b>Marina Souza</b><span>Operadora</span><label><input type="checkbox" defaultChecked/> Registrar entradas e saídas</label><label><input type="checkbox" defaultChecked/> Consultar estoque</label><label><input type="checkbox"/> Ver histórico geral</label><label><input type="checkbox"/> Gerar Excel</label><button className="outline-button">Salvar permissões</button></div></article></div>}
function Header({title,text}:{title:string;text:string}){return <div className="card-title"><div><h2>{title}</h2><p>{text}</p></div></div>}
function Form({title,submit,fields}:{title:string;submit:(e:FormEvent<HTMLFormElement>)=>void;fields:string[][]}){return <article className="card form-card"><Header title={title} text="Preencha os dados abaixo."/><form onSubmit={submit}>{fields.map(x=><label key={x[0]}>{x[1]}<input name={x[0]} type={x[2]||'text'} required/></label>)}<button className="primary-button">Salvar cadastro</button></form></article>}
function History({rows}:{rows:Movement[]}){return <div className="table-wrap"><table><thead><tr><th>TIPO</th><th>PRODUTO</th><th>ORIGEM</th><th>DESTINO</th><th>QUANTIDADE</th><th>RESPONSÁVEL</th><th>DATA</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><span className={'badge '+(x.tipo==='Entrada'?'good':'critical')}>{x.tipo}</span></td><td><strong>{x.produto}</strong></td><td>{x.origem}</td><td>{x.destino}</td><td>{x.quantidade} un.</td><td>{x.responsavel}</td><td>{x.data}</td></tr>):<tr><td colSpan={7}>Nenhum registro encontrado.</td></tr>}</tbody></table></div>}
function Stat({title,value}:{title:string;value:string}){return <article className="stat-card"><div className="stat-icon red">★</div><div><p>{title}</p><strong>{value}</strong><small className="positive">Atualizado agora</small></div></article>}
