# Generated by Django 6.1 on 2026-08-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='local_destino',
            field=models.CharField(default='Não informado', max_length=180),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='local_origem',
            field=models.CharField(default='Não informado', max_length=180),
        ),
    ]
